### PR TITLE
feat: force park removes FTR; can batch

### PR DESCRIPTION
**Pull request by dtbuchholz**
- Changed `parkRig` to no longer need `sender` (it was unused) and instead, take a `bool` for if the parking is a force park or standard park
- Changed `parkRigAsOwner` to take an array and pass `true` to force `parkRig`
- Changed `parkRig` to set zero FTR if a Rig is force parked

### CODE REVIEW

**Review by sanderpick — APPROVED** [review]
lgtm! 💪

**Comment by dtbuchholz** [comment]
(Upgraded the mumbai contracts to reflect these changes)

**Review by sanderpick — APPROVED** [review]
👍

**Comment by sanderpick** [comment]
i'll publish a new pre package to npm w/ new mumbai tables once you merge this so we can see it in action in the garage / anim app

**Pull request merged**
