### PR TITLE
Add a way to give owners FT for off-chain work

### PR DESCRIPTION
**Pull request by datadanne**
Adds a way to give FT to owners for off-chain work.

- Adds a table to track off chain owner rewards (that is created by the rigs cli)
- Updates the garage owner profile with a table that lists FT rewards + updates total FT in header to include rewards
- Adds an /admin page to the garage with a form to insert an ft reward

It doesn't feel like we need a smart contract to own or control writing to the table since we will kind of do that at our own discretion in a centralized way. What do you think @sanderpick?

image
image

Closes RIG-15

~Blocked by RIG-36~

### CODE REVIEW

**Comment by sanderpick** [comment]
Looks good! So in short, we have a new table for FT rewards that we control.

Regarding the earlier comments around voting, I agree it would be nice to have a `vote_id` column on this table. We should probably wait until the voting mechanism has been scoped out to make sure all bases are covered.

**Comment by datadanne** [comment]
> Looks good! So in short, we have a new table for FT rewards that we control.
> 
> Regarding the earlier comments around voting, I agree it would be nice to have a vote_id column on this table. We should probably wait until the voting mechanism has been scoped out to make sure all bases are covered.

Yeah I agree, I've updated the voting design proposal to include a `proposal_id`/`vote_id` column in the ft rewards table & to write there so it would be nice to wait until we've agreed on a design there. Unless alter table support will be live soon, if so we could ship this first and add the additional column later

**Comment by sanderpick** [comment]
I think we should be pretty close to consensus on the voting mechanism.... may as well wait

**Comment by sanderpick** [comment]
hey @datadanne, do you think you can wrap this one up this week? we could ship next on tuesday

**Comment by datadanne** [comment]
> hey @datadanne, do you think you can wrap this one up this week? we could ship next on tuesday

Yeah we can! I just added a `proposal_id` column to the table & rebased the branch. One question: do you have a preference on having an explicit `id integer primary key` column in the `ft_rewards` table or not? We have one for the pilot sessions-table so I included one for consistency when I first opened this PR, but I haven't been able to test distributing FT rewards from the `VotingRegistry` contract end to end with a primary key on the `ft_rewards` table. `INSERT INTO x SELECT`-statements don't get parsed correctly right now so they don't include the column name list in the query that gets passed to the db, and with the PK there rows can't be inserted since the db expects all columns to be provided if you don't include a named list. I have a proposed fix for the parser here: https://github.com/tablelandnetwork/go-sqlparser/pull/61, if that gets merged it Should:tm: work. I've tested it without the PK though and that works

**Comment by sanderpick** [comment]
Roger that! An `id` column would be nice for consistency. We could merge this to a staging branch and just have it ready for when the parser fix goes live.

**Comment by datadanne** [comment]
> Roger that! An `id` column would be nice for consistency. We could merge this to a staging branch and just have it ready for when the parser fix goes live. 

Sgtm! Want me to create a new staging branch based on main and change this PR to target staging?

**Comment by sanderpick** [comment]
> Sgtm! Want me to create a new staging branch based on main and change this PR to target staging?
Works for me

**Review by sanderpick — APPROVED** [review]

**Comment by datadanne** [comment]
> Works for me

Ah, I can't merge the PR because:
> Required statuses must pass before merging

**Comment by sanderpick** [comment]
all good, we can leave it like this and deal w/ that when deploying

**Review by joewagner — APPROVED** [review]

**Comment by joewagner** [comment]
This looks good to me!  
I see an error in the console when I change networks and when I look at my owner page: https://rigs-garage-7y9y8etk8-tableland.vercel.app/owner/0x1Ba0D9DdC122351316Ba663c2148269b32AA052c

Neither seem related to this though

**Comment by sanderpick** [comment]
- Tables created on Filecoin and Mumbai. I went with Filecoin to avoid having to move it over there after the Filecoin migration. 
- SDK updated to 4.3.2, which includes support for Filecoin
- Manually tested the vercel previews of the garage and animation URL

**Comment by sanderpick** [comment]
> This looks good to me! I see an error in the console when I change networks and when I look at my owner page: https://rigs-garage-7y9y8etk8-tableland.vercel.app/owner/0x1Ba0D9DdC122351316Ba663c2148269b32AA052c
> 
> Neither seem related to this though

oh yeah, that looks to be a deployment from the second to last commit... the SDK needed to be updated. Should work now: https://rigs-garage-git-datadanne-grant-ft-rewards-tableland.vercel.app/owner/0x1Ba0D9DdC122351316Ba663c2148269b32AA052c

Screenshot 2023-06-06 at 12 16 46 PM

(as in, the rewards table should correctly render)

**Comment by sanderpick** [comment]
I changed the base branch to main... @joewagner could I get another 👍 ?

**Review by joewagner — APPROVED** [review]

**Pull request merged**
