### PR TITLE
Garage: Add about pilots modal

### PR DESCRIPTION
**Pull request by datadanne**
Closes https://github.com/tablelandnetwork/rigs/issues/400

Update:
I took a stab at updating the copy/contents. I think we should try to explain what FT is, why you earn it for piloting, custom pilots, and that it requires on-chain transactions. Anything I'm missing? Or any feedback on the copy?
image

> ### Flight Time (FT)
> Flight Time is a non-transferrable reputation metric for the Tableland ecosystem (that is stored and tracked in Tableland!)
> 
> As a Rig owner you can earn FT by taking your Rigs flying. A Rig that is in-flight cannot be transferred or sold, and as a reward for taking your Rig off the market you earn FT (also referred to as soft-staking, the NFT doesn't leave your wallet but it is locked).
> 
> ### Pilots and training
> Every Rig must go through a training phase with a trainer pilot to re-learn how to fly. Training takes 172,800 blocks (about 30 days).
> 
> After training you can use any ERC721 token that you own to pilot your Rigs. Pilot history is stored on Tableland, and can be queried and reflected in metadata
> 
> ### How do I train/pilot my Rigs?
> Training, piloting and parking all require an on-chain transaction. This means that you will have to sign a transaction and pay a small gas every time you fee for every action you take.

~Any ideas about what we should write in the modal @sanderpick? Something about why earning FT is good, reputation, and info about 30 days of training unlocks custom pilots maybe? Do you want to take a stab at the copy?~

~I'm not 100% sure about the orange highlight color (it is the same color as the top bar on the Enter garage page) but it felt like we could use a stronger highlight than the italic text we use in the train/pilot modals.~

~Layout heavily inspired by the suggestion I got from PRISM, ht!~

image
image
image

### CODE REVIEW

**Review by sanderpick — DISMISSED** [review]
looks great. we could go with the modal text you have in there now and i could help w/ something more when back.. or maybe @andrewxhill has some sooner thoughts.

**Comment by andrewxhill** [comment]
That modal looks really good to me.

**Comment by sanderpick** [comment]
@datadanne can this be merged?

**Comment by datadanne** [comment]
@sanderpick I didn't feel like it was worth merging the PR with the copy that is in the PR since it is was just a copy of the train/pilot modal, I don't think it explains the feature very well. I worked on a suggestion today, what do you think about this?

image


> ### Flight Time (FT)
> Flight Time is a non-transferrable reputation metric for the Tableland ecosystem (that is stored and tracked in Tableland!)
> 
> As a Rig owner you can earn FT by taking your Rigs flying. A Rig that is in-flight cannot be transferred or sold, and as a reward for taking your Rig off the market you earn FT (also referred to as soft-staking, the NFT doesn't leave your wallet but it is locked).
> 
> ### Pilots and training
> Every Rig must go through a training phase with a trainer pilot to re-learn how to fly. Training takes 172,800 blocks (about 30 days).
> 
> After training you can use any ERC721 token that you own to pilot your Rigs. Pilot history is stored on Tableland, and can be queried and reflected in metadata
> 
> ### How do I train/pilot my Rigs?
> Training, piloting and parking all require an on-chain transaction. This means that you will have to sign a transaction and pay a small gas every time you fee for every action you take.

**Comment by sanderpick** [comment]
Looks great. Period missing on 1st and 4th paragraph.

**Review by sanderpick — APPROVED** [review]
Lgtm!

**Review by andrewxhill — APPROVED** [review]

**Comment by datadanne** [comment]
I realized that this should probably be a separate page instead of a modal (or maybe it can be both), but having a https://garage.tableland.xyz/about that we can link to in the discord and to anyone that asks about how the garage/FT/piloting works seems useful

**Pull request merged**
