### PR TITLE
Garage: Voting UI

### PR DESCRIPTION
**Pull request by datadanne**
Adds a proposals list page, a proposal details page where users can vote, and an form to the admin page to create proposals. Uses https://github.com/ipfs/helia to download ipfs markdown files 

~QUESTION: Anyone have experience with helia? It looks like it is the recommend way to interact with ipfs in the browser, the old https://github.com/ipfs/js-ipfs is deprecated/archived. But I don't know if using helia overkill and it would be better to just use a ipfs gateway and `fetch` it?~

~NOTE: Doesn't build right now because the `proposalsTable` etc are missing from the rigs package. Will not build until https://github.com/tablelandnetwork/rigs/pull/835 has been merged and published to npm.~

~NOTE: If you want to test this locally you'll have to either clone the repo twice or rebase it ontop of the `datadanne/voting` branch~

Screenshots:
image
image
image
image
image
image

Closes RIG-18, RIG-20

### CODE REVIEW

**Comment by datadanne** [comment]
I just rebased this on top of `staging`. Builds/deployments will still fail until we've merged the contract change and published a new version of the rigs package

**Comment by sanderpick** [comment]
cool. i can do a dev release from staging tomorrow if that would help?

**Comment by datadanne** [comment]
> cool. i can do a dev release from staging tomorrow if that would help?

yeah! we'll have to
- deploy everything that is in staging to main
- merge #835 into staging
- deploy the voting contract & tables for the staging environment & update the deployment info with the contract address & table names
- publish a dev release of rigs to npm

I can update this PR to use that dev release and it will be testable!

**Comment by datadanne** [comment]
I did some small fixes today:
- Fixed the markdown styling, tables and headings didn't look great
- Updated the markdown rendering to open links in new tabs
- Removed the helia sdk, I was getting weird browser warnings in chrome about the site being unsafe (from p2p-connections I think?) so I reverted to just using `fetch` to get the markdown doc from an ipfs gateway
- Updated to the dev build of the rigs package

This is what the proposal details page looks like with the newest changes, using the same markdown as we did for one of the pilot program snapshot votes (https://snapshot.org/#/tableland-rigs.eth/proposal/0xb8a671ea3763c68e0d97084c2261ad13175e650cd01d723dc67b003c86849512):
image

**Comment by sanderpick** [comment]
exciting! looks awesome

**Review by sanderpick — APPROVED** [review]

**Review by sanderpick — APPROVED** [review]

**Pull request merged**
